version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.1
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      - image: circleci/postgres:9.4

    working_directory: ~/fhir_server

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements/test.txt" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements/test.txt" }}
        
      # run tests!
      # this example uses Django's built-in test-runner
      # other common Python testing frameworks include pytest and nose
      # https://pytest.org
      # https://nose.readthedocs.io
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            python manage.py test

      - store_artifacts:
          path: test-reports
          destination: test-reports
          
#machine:
#  python:
#    version: '3.5.1'
#
#  environment:
#    DATABASE_URL: postgres://ubuntu:@127.0.0.1:5432/circle_test
#
#checkout:
#  post:
#    - git submodule sync
#    - git submodule update --init --recursive
#
#dependencies:
#  pre:
#    - sudo apt-get update
#    - sudo apt-get install python3-all-dev
#    - sudo apt-get install liburiparser-dev
#    - sudo apt-get install postgresql-server-dev-9.4
#    - cd lib/pguri && make && sudo make install
#    - psql -d postgres://ubuntu:@127.0.0.1:5432/circle_test -f ${HOME}/${CIRCLE_PROJECT_REPONAME}/fhir_server/elements/base/pg_types.sql
#
#test:
#  override:
#    - tox:
#        environment:
#          TEST_DATABASE_URL: postgres://ubuntu:@127.0.0.1:5432/circle_test
#          APP_SETTINGS: fhir_server.configs.base.DevelopmentConfig
#          TEST_SETTINGS: fhir_server.configs.base.TestingConfig