"""Add ValuesetsResource

Revision ID: 9f903c1902e9
Revises: 8a61f5fb05a8
Create Date: 2016-06-30 16:34:17.720809

"""

# revision identifiers, used by Alembic.
revision = "9f903c1902e9"
down_revision = "8a61f5fb05a8"

from alembic import op
import sqlalchemy as sa
from sqlalchemy import Column
import sqlalchemy_utils
from sqlalchemy_utils import CompositeArray, JSONType

import fhir_server
from fhir_server.elements.primitives import *
from fhir_server.elements.opentype import OpenType
from fhir_server.elements.base.complex_mixin import PgComposite


from fhir_server.resources import all_resources, constraints


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "valueset",
        sa.Column("id", fhir_server.elements.primitives.IdField(), nullable=False),
        sa.Column(
            "implicitRules", fhir_server.elements.primitives.URIField(), nullable=True
        ),
        sa.Column(
            "language", fhir_server.elements.primitives.CodeField(), nullable=True
        ),
        sa.Column("url", fhir_server.elements.primitives.URIField(), nullable=True),
        sa.Column(
            "version", fhir_server.elements.primitives.StringField(), nullable=True
        ),
        sa.Column("name", fhir_server.elements.primitives.StringField(), nullable=True),
        sa.Column(
            "status", fhir_server.elements.primitives.CodeField(), nullable=False
        ),
        sa.Column(
            "experimental",
            fhir_server.elements.primitives.BooleanField(),
            nullable=True,
        ),
        sa.Column(
            "publisher", fhir_server.elements.primitives.StringField(), nullable=True
        ),
        sa.Column(
            "date",
            fhir_server.elements.primitives.DateTimeField(timezone=True),
            nullable=True,
        ),
        sa.Column(
            "lockedDate", fhir_server.elements.primitives.DateField(), nullable=True
        ),
        sa.Column(
            "description", fhir_server.elements.primitives.StringField(), nullable=True
        ),
        sa.Column(
            "immutable", fhir_server.elements.primitives.BooleanField(), nullable=True
        ),
        sa.Column(
            "requirements", fhir_server.elements.primitives.StringField(), nullable=True
        ),
        sa.Column(
            "copyright", fhir_server.elements.primitives.StringField(), nullable=True
        ),
        sa.Column(
            "extensible", fhir_server.elements.primitives.BooleanField(), nullable=True
        ),
        sa.Column(
            "identifier",
            fhir_server.elements.base.complex_mixin.PgComposite(
                "fhir_identifier",
                [
                    Column(
                        "extension",
                        PgComposite(
                            "fhir_extension",
                            [
                                Column("url", StringField(), nullable=False),
                                Column("value", OpenType()),
                            ],
                        ),
                    ),
                    Column("id", StringField()),
                    Column("system", URIField()),
                    Column("use", CodeField()),
                    Column("value", StringField()),
                    Column(
                        "assigner",
                        PgComposite(
                            "fhir_reference",
                            [
                                Column(
                                    "extension",
                                    PgComposite(
                                        "fhir_extension",
                                        [
                                            Column(
                                                "url", StringField(), nullable=False
                                            ),
                                            Column("value", OpenType()),
                                        ],
                                    ),
                                ),
                                Column("id", StringField()),
                                Column("display", StringField()),
                                Column("reference", StringField()),
                            ],
                        ),
                    ),
                    Column(
                        "period",
                        PgComposite(
                            "fhir_period",
                            [
                                Column(
                                    "extension",
                                    PgComposite(
                                        "fhir_extension",
                                        [
                                            Column(
                                                "url", StringField(), nullable=False
                                            ),
                                            Column("value", OpenType()),
                                        ],
                                    ),
                                ),
                                Column("id", StringField()),
                                Column("end_time", DateTimeField(timezone=True)),
                                Column("start_time", DateTimeField(timezone=True)),
                            ],
                        ),
                    ),
                    Column(
                        "type",
                        PgComposite(
                            "fhir_codeableconcept",
                            [
                                Column(
                                    "extension",
                                    PgComposite(
                                        "fhir_extension",
                                        [
                                            Column(
                                                "url", StringField(), nullable=False
                                            ),
                                            Column("value", OpenType()),
                                        ],
                                    ),
                                ),
                                Column("id", StringField()),
                                Column("text", StringField()),
                                Column(
                                    "coding",
                                    CompositeArray(
                                        PgComposite(
                                            "fhir_coding",
                                            [
                                                Column(
                                                    "extension",
                                                    PgComposite(
                                                        "fhir_extension",
                                                        [
                                                            Column(
                                                                "url",
                                                                StringField(),
                                                                nullable=False,
                                                            ),
                                                            Column("value", OpenType()),
                                                        ],
                                                    ),
                                                ),
                                                Column("id", StringField()),
                                                Column("code", CodeField()),
                                                Column("display", StringField()),
                                                Column("system", URIField()),
                                                Column("user_selected", BooleanField()),
                                                Column("version", StringField()),
                                            ],
                                        )
                                    ),
                                ),
                            ],
                        ),
                    ),
                ],
            ),
            nullable=True,
        ),
        sa.Column(
            "contact",
            sqlalchemy_utils.types.pg_composite.CompositeArray(
                PgComposite(
                    "fhir_valuesetcontact",
                    [
                        Column(
                            "extension",
                            PgComposite(
                                "fhir_extension",
                                [
                                    Column("url", StringField(), nullable=False),
                                    Column("value", OpenType()),
                                ],
                            ),
                        ),
                        Column("id", StringField()),
                        Column("name", StringField()),
                        Column(
                            "telecom",
                            CompositeArray(
                                PgComposite(
                                    "fhir_contactpoint",
                                    [
                                        Column(
                                            "extension",
                                            PgComposite(
                                                "fhir_extension",
                                                [
                                                    Column(
                                                        "url",
                                                        StringField(),
                                                        nullable=False,
                                                    ),
                                                    Column("value", OpenType()),
                                                ],
                                            ),
                                        ),
                                        Column("id", StringField()),
                                        Column("rank", PositiveIntField()),
                                        Column("system", CodeField()),
                                        Column("use", CodeField()),
                                        Column("value", StringField()),
                                        Column(
                                            "period",
                                            PgComposite(
                                                "fhir_period",
                                                [
                                                    Column(
                                                        "extension",
                                                        PgComposite(
                                                            "fhir_extension",
                                                            [
                                                                Column(
                                                                    "url",
                                                                    StringField(),
                                                                    nullable=False,
                                                                ),
                                                                Column(
                                                                    "value", OpenType()
                                                                ),
                                                            ],
                                                        ),
                                                    ),
                                                    Column("id", StringField()),
                                                    Column(
                                                        "end_time",
                                                        DateTimeField(timezone=True),
                                                    ),
                                                    Column(
                                                        "start_time",
                                                        DateTimeField(timezone=True),
                                                    ),
                                                ],
                                            ),
                                        ),
                                    ],
                                )
                            ),
                        ),
                    ],
                )
            ),
            nullable=True,
        ),
        sa.Column(
            "useContext",
            sqlalchemy_utils.types.pg_composite.CompositeArray(
                PgComposite(
                    "fhir_codeableconcept",
                    [
                        Column(
                            "extension",
                            PgComposite(
                                "fhir_extension",
                                [
                                    Column("url", StringField(), nullable=False),
                                    Column("value", OpenType()),
                                ],
                            ),
                        ),
                        Column("id", StringField()),
                        Column("text", StringField()),
                        Column(
                            "coding",
                            CompositeArray(
                                PgComposite(
                                    "fhir_coding",
                                    [
                                        Column(
                                            "extension",
                                            PgComposite(
                                                "fhir_extension",
                                                [
                                                    Column(
                                                        "url",
                                                        StringField(),
                                                        nullable=False,
                                                    ),
                                                    Column("value", OpenType()),
                                                ],
                                            ),
                                        ),
                                        Column("id", StringField()),
                                        Column("code", CodeField()),
                                        Column("display", StringField()),
                                        Column("system", URIField()),
                                        Column("user_selected", BooleanField()),
                                        Column("version", StringField()),
                                    ],
                                )
                            ),
                        ),
                    ],
                )
            ),
            nullable=True,
        ),
        sa.Column(
            "codeSystem",
            fhir_server.elements.base.complex_mixin.PgComposite(
                "fhir_valuesetcodesystem",
                [
                    Column(
                        "extension",
                        PgComposite(
                            "fhir_extension",
                            [
                                Column("url", StringField(), nullable=False),
                                Column("value", OpenType()),
                            ],
                        ),
                    ),
                    Column("id", StringField()),
                    Column("system", URIField(), nullable=False),
                    Column("version", StringField()),
                    Column("caseSensitive", BooleanField()),
                    Column(
                        "concept",
                        CompositeArray(
                            PgComposite(
                                "fhir_valuesetcodesystemconcept",
                                [
                                    Column(
                                        "extension",
                                        PgComposite(
                                            "fhir_extension",
                                            [
                                                Column(
                                                    "url", StringField(), nullable=False
                                                ),
                                                Column("value", OpenType()),
                                            ],
                                        ),
                                    ),
                                    Column("id", StringField()),
                                    Column("code", CodeField(), nullable=False),
                                    Column("abstract", BooleanField()),
                                    Column("display", StringField()),
                                    Column("definition", StringField()),
                                    Column("concept", CompositeArray(StringField())),
                                    Column(
                                        "designation",
                                        PgComposite(
                                            "fhir_valuesetcodesystemconceptdesignation",
                                            [
                                                Column(
                                                    "extension",
                                                    PgComposite(
                                                        "fhir_extension",
                                                        [
                                                            Column(
                                                                "url",
                                                                StringField(),
                                                                nullable=False,
                                                            ),
                                                            Column("value", OpenType()),
                                                        ],
                                                    ),
                                                ),
                                                Column("id", StringField()),
                                                Column("language", StringField()),
                                                Column(
                                                    "value",
                                                    StringField(),
                                                    nullable=False,
                                                ),
                                                Column(
                                                    "use",
                                                    PgComposite(
                                                        "fhir_coding",
                                                        [
                                                            Column(
                                                                "extension",
                                                                PgComposite(
                                                                    "fhir_extension",
                                                                    [
                                                                        Column(
                                                                            "url",
                                                                            StringField(),
                                                                            nullable=False,
                                                                        ),
                                                                        Column(
                                                                            "value",
                                                                            OpenType(),
                                                                        ),
                                                                    ],
                                                                ),
                                                            ),
                                                            Column("id", StringField()),
                                                            Column("code", CodeField()),
                                                            Column(
                                                                "display", StringField()
                                                            ),
                                                            Column(
                                                                "system", URIField()
                                                            ),
                                                            Column(
                                                                "user_selected",
                                                                BooleanField(),
                                                            ),
                                                            Column(
                                                                "version", StringField()
                                                            ),
                                                        ],
                                                    ),
                                                ),
                                            ],
                                        ),
                                    ),
                                ],
                            )
                        ),
                    ),
                ],
            ),
            nullable=True,
        ),
        sa.Column(
            "compose",
            fhir_server.elements.base.complex_mixin.PgComposite(
                "fhir_valuesetcompose",
                [
                    Column(
                        "extension",
                        PgComposite(
                            "fhir_extension",
                            [
                                Column("url", StringField(), nullable=False),
                                Column("value", OpenType()),
                            ],
                        ),
                    ),
                    Column("id", StringField()),
                    Column("compose_import", CompositeArray(URIField())),
                    Column(
                        "include",
                        CompositeArray(
                            PgComposite(
                                "fhir_valuesetcomposeinclude",
                                [
                                    Column(
                                        "extension",
                                        PgComposite(
                                            "fhir_extension",
                                            [
                                                Column(
                                                    "url", StringField(), nullable=False
                                                ),
                                                Column("value", OpenType()),
                                            ],
                                        ),
                                    ),
                                    Column("id", StringField()),
                                    Column("system", CodeField(), nullable=False),
                                    Column("version", CodeField()),
                                    Column(
                                        "concept",
                                        CompositeArray(
                                            PgComposite(
                                                "fhir_valuesetcomposeincludeconcept",
                                                [
                                                    Column(
                                                        "extension",
                                                        PgComposite(
                                                            "fhir_extension",
                                                            [
                                                                Column(
                                                                    "url",
                                                                    StringField(),
                                                                    nullable=False,
                                                                ),
                                                                Column(
                                                                    "value", OpenType()
                                                                ),
                                                            ],
                                                        ),
                                                    ),
                                                    Column("id", StringField()),
                                                    Column(
                                                        "code",
                                                        StringField(),
                                                        nullable=False,
                                                    ),
                                                    Column("display", StringField()),
                                                    Column(
                                                        "designation",
                                                        CompositeArray(
                                                            PgComposite(
                                                                "fhir_valuesetcodesystemconceptdesignation",
                                                                [
                                                                    Column(
                                                                        "extension",
                                                                        PgComposite(
                                                                            "fhir_extension",
                                                                            [
                                                                                Column(
                                                                                    "url",
                                                                                    StringField(),
                                                                                    nullable=False,
                                                                                ),
                                                                                Column(
                                                                                    "value",
                                                                                    OpenType(),
                                                                                ),
                                                                            ],
                                                                        ),
                                                                    ),
                                                                    Column(
                                                                        "id",
                                                                        StringField(),
                                                                    ),
                                                                    Column(
                                                                        "language",
                                                                        StringField(),
                                                                    ),
                                                                    Column(
                                                                        "value",
                                                                        StringField(),
                                                                        nullable=False,
                                                                    ),
                                                                    Column(
                                                                        "use",
                                                                        PgComposite(
                                                                            "fhir_coding",
                                                                            [
                                                                                Column(
                                                                                    "extension",
                                                                                    PgComposite(
                                                                                        "fhir_extension",
                                                                                        [
                                                                                            Column(
                                                                                                "url",
                                                                                                StringField(),
                                                                                                nullable=False,
                                                                                            ),
                                                                                            Column(
                                                                                                "value",
                                                                                                OpenType(),
                                                                                            ),
                                                                                        ],
                                                                                    ),
                                                                                ),
                                                                                Column(
                                                                                    "id",
                                                                                    StringField(),
                                                                                ),
                                                                                Column(
                                                                                    "code",
                                                                                    CodeField(),
                                                                                ),
                                                                                Column(
                                                                                    "display",
                                                                                    StringField(),
                                                                                ),
                                                                                Column(
                                                                                    "system",
                                                                                    URIField(),
                                                                                ),
                                                                                Column(
                                                                                    "user_selected",
                                                                                    BooleanField(),
                                                                                ),
                                                                                Column(
                                                                                    "version",
                                                                                    StringField(),
                                                                                ),
                                                                            ],
                                                                        ),
                                                                    ),
                                                                ],
                                                            )
                                                        ),
                                                    ),
                                                ],
                                            )
                                        ),
                                    ),
                                    Column(
                                        "filter",
                                        CompositeArray(
                                            PgComposite(
                                                "fhir_valuesetcomposeincludefilter",
                                                [
                                                    Column(
                                                        "extension",
                                                        PgComposite(
                                                            "fhir_extension",
                                                            [
                                                                Column(
                                                                    "url",
                                                                    StringField(),
                                                                    nullable=False,
                                                                ),
                                                                Column(
                                                                    "value", OpenType()
                                                                ),
                                                            ],
                                                        ),
                                                    ),
                                                    Column("id", StringField()),
                                                    Column(
                                                        "op",
                                                        CodeField(),
                                                        nullable=False,
                                                    ),
                                                    Column(
                                                        "property",
                                                        CodeField(),
                                                        nullable=False,
                                                    ),
                                                    Column(
                                                        "value",
                                                        CodeField(),
                                                        nullable=False,
                                                    ),
                                                ],
                                            )
                                        ),
                                    ),
                                ],
                            )
                        ),
                    ),
                    Column(
                        "exclude",
                        CompositeArray(
                            PgComposite(
                                "fhir_valuesetcomposeinclude",
                                [
                                    Column(
                                        "extension",
                                        PgComposite(
                                            "fhir_extension",
                                            [
                                                Column(
                                                    "url", StringField(), nullable=False
                                                ),
                                                Column("value", OpenType()),
                                            ],
                                        ),
                                    ),
                                    Column("id", StringField()),
                                    Column("system", CodeField(), nullable=False),
                                    Column("version", CodeField()),
                                    Column(
                                        "concept",
                                        CompositeArray(
                                            PgComposite(
                                                "fhir_valuesetcomposeincludeconcept",
                                                [
                                                    Column(
                                                        "extension",
                                                        PgComposite(
                                                            "fhir_extension",
                                                            [
                                                                Column(
                                                                    "url",
                                                                    StringField(),
                                                                    nullable=False,
                                                                ),
                                                                Column(
                                                                    "value", OpenType()
                                                                ),
                                                            ],
                                                        ),
                                                    ),
                                                    Column("id", StringField()),
                                                    Column(
                                                        "code",
                                                        StringField(),
                                                        nullable=False,
                                                    ),
                                                    Column("display", StringField()),
                                                    Column(
                                                        "designation",
                                                        CompositeArray(
                                                            PgComposite(
                                                                "fhir_valuesetcodesystemconceptdesignation",
                                                                [
                                                                    Column(
                                                                        "extension",
                                                                        PgComposite(
                                                                            "fhir_extension",
                                                                            [
                                                                                Column(
                                                                                    "url",
                                                                                    StringField(),
                                                                                    nullable=False,
                                                                                ),
                                                                                Column(
                                                                                    "value",
                                                                                    OpenType(),
                                                                                ),
                                                                            ],
                                                                        ),
                                                                    ),
                                                                    Column(
                                                                        "id",
                                                                        StringField(),
                                                                    ),
                                                                    Column(
                                                                        "language",
                                                                        StringField(),
                                                                    ),
                                                                    Column(
                                                                        "value",
                                                                        StringField(),
                                                                        nullable=False,
                                                                    ),
                                                                    Column(
                                                                        "use",
                                                                        PgComposite(
                                                                            "fhir_coding",
                                                                            [
                                                                                Column(
                                                                                    "extension",
                                                                                    PgComposite(
                                                                                        "fhir_extension",
                                                                                        [
                                                                                            Column(
                                                                                                "url",
                                                                                                StringField(),
                                                                                                nullable=False,
                                                                                            ),
                                                                                            Column(
                                                                                                "value",
                                                                                                OpenType(),
                                                                                            ),
                                                                                        ],
                                                                                    ),
                                                                                ),
                                                                                Column(
                                                                                    "id",
                                                                                    StringField(),
                                                                                ),
                                                                                Column(
                                                                                    "code",
                                                                                    CodeField(),
                                                                                ),
                                                                                Column(
                                                                                    "display",
                                                                                    StringField(),
                                                                                ),
                                                                                Column(
                                                                                    "system",
                                                                                    URIField(),
                                                                                ),
                                                                                Column(
                                                                                    "user_selected",
                                                                                    BooleanField(),
                                                                                ),
                                                                                Column(
                                                                                    "version",
                                                                                    StringField(),
                                                                                ),
                                                                            ],
                                                                        ),
                                                                    ),
                                                                ],
                                                            )
                                                        ),
                                                    ),
                                                ],
                                            )
                                        ),
                                    ),
                                    Column(
                                        "filter",
                                        CompositeArray(
                                            PgComposite(
                                                "fhir_valuesetcomposeincludefilter",
                                                [
                                                    Column(
                                                        "extension",
                                                        PgComposite(
                                                            "fhir_extension",
                                                            [
                                                                Column(
                                                                    "url",
                                                                    StringField(),
                                                                    nullable=False,
                                                                ),
                                                                Column(
                                                                    "value", OpenType()
                                                                ),
                                                            ],
                                                        ),
                                                    ),
                                                    Column("id", StringField()),
                                                    Column(
                                                        "op",
                                                        CodeField(),
                                                        nullable=False,
                                                    ),
                                                    Column(
                                                        "property",
                                                        CodeField(),
                                                        nullable=False,
                                                    ),
                                                    Column(
                                                        "value",
                                                        CodeField(),
                                                        nullable=False,
                                                    ),
                                                ],
                                            )
                                        ),
                                    ),
                                ],
                            )
                        ),
                    ),
                ],
            ),
            nullable=True,
        ),
        sa.Column(
            "expansion",
            fhir_server.elements.base.complex_mixin.PgComposite(
                "fhir_valuesetexpansion",
                [
                    Column(
                        "extension",
                        PgComposite(
                            "fhir_extension",
                            [
                                Column("url", StringField(), nullable=False),
                                Column("value", OpenType()),
                            ],
                        ),
                    ),
                    Column("id", StringField()),
                    Column("identifier", URIField(), nullable=False),
                    Column("timestamp", DateTimeField(timezone=True), nullable=False),
                    Column("offset", IntegerField()),
                    Column("total", IntegerField()),
                    Column(
                        "parameter",
                        PgComposite(
                            "fhir_valuesetexpansionparameter",
                            [
                                Column(
                                    "extension",
                                    PgComposite(
                                        "fhir_extension",
                                        [
                                            Column(
                                                "url", StringField(), nullable=False
                                            ),
                                            Column("value", OpenType()),
                                        ],
                                    ),
                                ),
                                Column("id", StringField()),
                                Column("name", StringField(), nullable=False),
                                Column("valueBoolean", BooleanField()),
                                Column("valueCode", CodeField()),
                                Column("valueDecimal", DecimalField()),
                                Column("valueInteger", IntegerField()),
                                Column("valueString", StringField()),
                                Column("valueUri", URIField()),
                            ],
                        ),
                    ),
                    Column(
                        "contains",
                        PgComposite(
                            "fhir_valuesetexpansioncontains",
                            [
                                Column(
                                    "extension",
                                    PgComposite(
                                        "fhir_extension",
                                        [
                                            Column(
                                                "url", StringField(), nullable=False
                                            ),
                                            Column("value", OpenType()),
                                        ],
                                    ),
                                ),
                                Column("id", StringField()),
                                Column("abstract", BooleanField()),
                                Column("code", CodeField()),
                                Column("display", StringField()),
                                Column("system", URIField()),
                                Column("version", StringField()),
                                Column("contains", CompositeArray(StringField())),
                            ],
                        ),
                    ),
                ],
            ),
            nullable=True,
        ),
        sa.Column(
            "text",
            fhir_server.elements.base.complex_mixin.PgComposite(
                "fhir_narrative",
                [
                    Column(
                        "extension",
                        PgComposite(
                            "fhir_extension",
                            [
                                Column("url", StringField(), nullable=False),
                                Column("value", OpenType()),
                            ],
                        ),
                    ),
                    Column("id", StringField()),
                    Column("div", StringField(), nullable=False),
                    Column("status", CodeField(), nullable=False),
                ],
            ),
            nullable=True,
        ),
        sa.Column(
            "contained",
            sqlalchemy_utils.types.pg_composite.CompositeArray(JSONType()),
            nullable=True,
        ),
        sa.Column(
            "modifierExtension",
            sqlalchemy_utils.types.pg_composite.CompositeArray(
                PgComposite(
                    "fhir_extension",
                    [
                        Column("url", StringField(), nullable=False),
                        Column("value", OpenType()),
                    ],
                )
            ),
            nullable=True,
        ),
        sa.Column(
            "extension",
            sqlalchemy_utils.types.pg_composite.CompositeArray(
                PgComposite(
                    "fhir_extension",
                    [
                        Column("url", StringField(), nullable=False),
                        Column("value", OpenType()),
                    ],
                )
            ),
            nullable=True,
        ),
        sa.Column(
            "meta",
            fhir_server.elements.base.complex_mixin.PgComposite(
                "fhir_meta",
                [
                    Column(
                        "extension",
                        PgComposite(
                            "fhir_extension",
                            [
                                Column("url", StringField(), nullable=False),
                                Column("value", OpenType()),
                            ],
                        ),
                    ),
                    Column("id", StringField()),
                    Column("version_id", IdField()),
                    Column("last_updated", InstantField(timezone=True)),
                    Column("profile", CompositeArray(URIField())),
                    Column(
                        "security",
                        CompositeArray(
                            PgComposite(
                                "fhir_coding",
                                [
                                    Column(
                                        "extension",
                                        PgComposite(
                                            "fhir_extension",
                                            [
                                                Column(
                                                    "url", StringField(), nullable=False
                                                ),
                                                Column("value", OpenType()),
                                            ],
                                        ),
                                    ),
                                    Column("id", StringField()),
                                    Column("code", CodeField()),
                                    Column("display", StringField()),
                                    Column("system", URIField()),
                                    Column("user_selected", BooleanField()),
                                    Column("version", StringField()),
                                ],
                            )
                        ),
                    ),
                    Column(
                        "tag",
                        CompositeArray(
                            PgComposite(
                                "fhir_coding",
                                [
                                    Column(
                                        "extension",
                                        PgComposite(
                                            "fhir_extension",
                                            [
                                                Column(
                                                    "url", StringField(), nullable=False
                                                ),
                                                Column("value", OpenType()),
                                            ],
                                        ),
                                    ),
                                    Column("id", StringField()),
                                    Column("code", CodeField()),
                                    Column("display", StringField()),
                                    Column("system", URIField()),
                                    Column("user_selected", BooleanField()),
                                    Column("version", StringField()),
                                ],
                            )
                        ),
                    ),
                ],
            ),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    ### end Alembic commands ###

    conn = op.get_bind()
    for resource in all_resources:
        conn.execute(
            sa.sql.text(
                """
            DROP INDEX IF EXISTS {0}_meta_version_id;

            CREATE UNIQUE INDEX {0}_meta_version_id ON {0} (
                ((meta).version_id));

            DROP TRIGGER IF EXISTS meta_version_id_concurrency ON {0};

            CREATE TRIGGER meta_version_id_concurrency BEFORE INSERT OR UPDATE ON {0}
            FOR EACH ROW EXECUTE PROCEDURE meta_version_id_concurrency();
            """.format(
                    resource.__tablename__
                )
            )
        )

    profiled_resources = {con.get("resource"): con.get("fields") for con in constraints}
    for resource, const in profiled_resources.items():
        for c in const:
            field = c.get("name")
            mini = str(c.get("cardinality").get("mini"))
            maxi = str(c.get("cardinality").get("maxi"))
            conn.execute(
                sa.sql.text(
                    """
                DROP TRIGGER IF EXISTS validate_meta_fields_{1} ON {0};

                CREATE TRIGGER validate_meta_fields_{1} BEFORE INSERT OR UPDATE ON {0}
                FOR EACH ROW EXECUTE PROCEDURE validate_meta_fields({1}, '{2}', '{3}');
                """.format(
                        resource.lower(), field, mini, maxi
                    )
                )
            )


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("valueset")
    ### end Alembic commands ###
